name: appgiaohang
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  badges: ^3.1.2
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  intl: ^0.20.1
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  vietmap_flutter_navigation: ^3.3.1
  flutter_svg: ^2.0.16
  vietmap_flutter_gl: ^3.1.1
  flutter_polyline_points: ^2.1.0
  socket_io_client: ^3.0.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  file_picker: ^8.1.7
  path: ^1.9.0
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.6
  agora_rtc_engine: ^6.5.0
  logging: ^1.3.0
  dio: ^5.7.0
  flutter_stripe: ^11.3.0
  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/navigation_symbol/
    - assets/store_marker.png
    - assets/customer_marker.png
    - assets/images/shop_food_image.png
    - assets/images/food_image.png
