name: Run Local API Tests with Postman Cloud

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./giaohangbackend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install node-pre-gyp globally
        run: sudo npm install -g node-pre-gyp

      - name: Rebuild bcrypt
        run: npm rebuild bcrypt --build-from-source

      - name: Start server in background
        run: |
          nohup node index.js &
          sleep 10

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | bash

      - name: Install Postman Agent
        run: |
          curl -s https://dl.pstmn.io/agent/install.sh | bash

      - name: Start Postman Agent
        run: |
          postman agent start

      - name: Run Postman API Tests with API Key
        run: |
          postman login --with-api-key ${{ secrets.TOKENLOGIN }}
          postman collection run ${{ secrets.TOKENCOL }}

